name: base    # install straight into the default conda env
channels:
  - conda-forge
dependencies:
  # ---------- core interpreter ----------
  - python = 3.11
  - r-base            # pulls R 4.4 on conda-forge
  # ---------- python libs ----------
  - pandas = 2.1.4
  - sqlalchemy = 1.4.49
  - snowflake-sqlalchemy = 1.5.1
  - xgboost = 2.0.3
  - seaborn
  - joblib = 1.3.2
  - ipywidgets >=7.6
  - tabulate = 0.9.0
  - pip
  # ---------- R libs ----------
  - r-irkernel
  - r-remotes
  - r-languageserver
  - r-reticulate
  - r-dataexplorer
  - r-dplyr
  - r-kableextra
  - r-summarytools
  - r-hmisc
  - r-lubridate
  - r-plotly
  # ---------- system headers for R packages ----------
  - libxml2
  - cairo
  - freetype
  - fontconfig
  - glpk
  - gcc                # gives gfortran too
  # ---------- pip-only ----------
  - pip:
      - "u8darts[notorch]==0.25.0"
      - "python-dotenv>=0.20.0,<0.21.1"
